name: DICE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - matplotlib
  - scikit-learn
  - pandas
  - networkx
  - sympy
  - jinja2
  - pyyaml
  - tqdm
  - psutil
  - protobuf
  - filelock
  - requests
  - click
  - packaging
  - joblib
  - gitpython
  - docker-pycreds
  - sentry-sdk
  - setproctitle
  - six
  - pip:
      - wandb
      - torcheval
      - torch==2.2.0+cu121
      - torchvision==0.17.0+cu121
      - torch-scatter
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - -f https://data.pyg.org/whl/torch-2.2.0+cu121.html
